dist: bionic
language: go
go: '1.13.x'
env:
  - GO111MODULE=on
  - GOFLAGS='-mod vendor'
notifications:
  email: false
before_script:
  - go install github.com/golangci/golangci-lint/cmd/golangci-lint
script:
  - golangci-lint run