// Code generated by protoc-gen-go. DO NOT EDIT.
// source: database.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type DatabaseEmpty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DatabaseEmpty) Reset()         { *m = DatabaseEmpty{} }
func (m *DatabaseEmpty) String() string { return proto.CompactTextString(m) }
func (*DatabaseEmpty) ProtoMessage()    {}
func (*DatabaseEmpty) Descriptor() ([]byte, []int) {
	return fileDescriptor_b90fe3356ea5df07, []int{0}
}

func (m *DatabaseEmpty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DatabaseEmpty.Unmarshal(m, b)
}
func (m *DatabaseEmpty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DatabaseEmpty.Marshal(b, m, deterministic)
}
func (m *DatabaseEmpty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DatabaseEmpty.Merge(m, src)
}
func (m *DatabaseEmpty) XXX_Size() int {
	return xxx_messageInfo_DatabaseEmpty.Size(m)
}
func (m *DatabaseEmpty) XXX_DiscardUnknown() {
	xxx_messageInfo_DatabaseEmpty.DiscardUnknown(m)
}

var xxx_messageInfo_DatabaseEmpty proto.InternalMessageInfo

type DatabaseResponse struct {
	Result               []byte   `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DatabaseResponse) Reset()         { *m = DatabaseResponse{} }
func (m *DatabaseResponse) String() string { return proto.CompactTextString(m) }
func (*DatabaseResponse) ProtoMessage()    {}
func (*DatabaseResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b90fe3356ea5df07, []int{1}
}

func (m *DatabaseResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DatabaseResponse.Unmarshal(m, b)
}
func (m *DatabaseResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DatabaseResponse.Marshal(b, m, deterministic)
}
func (m *DatabaseResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DatabaseResponse.Merge(m, src)
}
func (m *DatabaseResponse) XXX_Size() int {
	return xxx_messageInfo_DatabaseResponse.Size(m)
}
func (m *DatabaseResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DatabaseResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DatabaseResponse proto.InternalMessageInfo

func (m *DatabaseResponse) GetResult() []byte {
	if m != nil {
		return m.Result
	}
	return nil
}

type DatabaseID struct {
	Value                uint64   `protobuf:"varint,1,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DatabaseID) Reset()         { *m = DatabaseID{} }
func (m *DatabaseID) String() string { return proto.CompactTextString(m) }
func (*DatabaseID) ProtoMessage()    {}
func (*DatabaseID) Descriptor() ([]byte, []int) {
	return fileDescriptor_b90fe3356ea5df07, []int{2}
}

func (m *DatabaseID) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DatabaseID.Unmarshal(m, b)
}
func (m *DatabaseID) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DatabaseID.Marshal(b, m, deterministic)
}
func (m *DatabaseID) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DatabaseID.Merge(m, src)
}
func (m *DatabaseID) XXX_Size() int {
	return xxx_messageInfo_DatabaseID.Size(m)
}
func (m *DatabaseID) XXX_DiscardUnknown() {
	xxx_messageInfo_DatabaseID.DiscardUnknown(m)
}

var xxx_messageInfo_DatabaseID proto.InternalMessageInfo

func (m *DatabaseID) GetValue() uint64 {
	if m != nil {
		return m.Value
	}
	return 0
}

type DatabaseIDs struct {
	Values               []uint64 `protobuf:"varint,1,rep,packed,name=values,proto3" json:"values,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DatabaseIDs) Reset()         { *m = DatabaseIDs{} }
func (m *DatabaseIDs) String() string { return proto.CompactTextString(m) }
func (*DatabaseIDs) ProtoMessage()    {}
func (*DatabaseIDs) Descriptor() ([]byte, []int) {
	return fileDescriptor_b90fe3356ea5df07, []int{3}
}

func (m *DatabaseIDs) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DatabaseIDs.Unmarshal(m, b)
}
func (m *DatabaseIDs) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DatabaseIDs.Marshal(b, m, deterministic)
}
func (m *DatabaseIDs) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DatabaseIDs.Merge(m, src)
}
func (m *DatabaseIDs) XXX_Size() int {
	return xxx_messageInfo_DatabaseIDs.Size(m)
}
func (m *DatabaseIDs) XXX_DiscardUnknown() {
	xxx_messageInfo_DatabaseIDs.DiscardUnknown(m)
}

var xxx_messageInfo_DatabaseIDs proto.InternalMessageInfo

func (m *DatabaseIDs) GetValues() []uint64 {
	if m != nil {
		return m.Values
	}
	return nil
}

type DatabaseString struct {
	Value                string   `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DatabaseString) Reset()         { *m = DatabaseString{} }
func (m *DatabaseString) String() string { return proto.CompactTextString(m) }
func (*DatabaseString) ProtoMessage()    {}
func (*DatabaseString) Descriptor() ([]byte, []int) {
	return fileDescriptor_b90fe3356ea5df07, []int{4}
}

func (m *DatabaseString) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DatabaseString.Unmarshal(m, b)
}
func (m *DatabaseString) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DatabaseString.Marshal(b, m, deterministic)
}
func (m *DatabaseString) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DatabaseString.Merge(m, src)
}
func (m *DatabaseString) XXX_Size() int {
	return xxx_messageInfo_DatabaseString.Size(m)
}
func (m *DatabaseString) XXX_DiscardUnknown() {
	xxx_messageInfo_DatabaseString.DiscardUnknown(m)
}

var xxx_messageInfo_DatabaseString proto.InternalMessageInfo

func (m *DatabaseString) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type DatabaseStrings struct {
	Values               []string `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DatabaseStrings) Reset()         { *m = DatabaseStrings{} }
func (m *DatabaseStrings) String() string { return proto.CompactTextString(m) }
func (*DatabaseStrings) ProtoMessage()    {}
func (*DatabaseStrings) Descriptor() ([]byte, []int) {
	return fileDescriptor_b90fe3356ea5df07, []int{5}
}

func (m *DatabaseStrings) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DatabaseStrings.Unmarshal(m, b)
}
func (m *DatabaseStrings) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DatabaseStrings.Marshal(b, m, deterministic)
}
func (m *DatabaseStrings) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DatabaseStrings.Merge(m, src)
}
func (m *DatabaseStrings) XXX_Size() int {
	return xxx_messageInfo_DatabaseStrings.Size(m)
}
func (m *DatabaseStrings) XXX_DiscardUnknown() {
	xxx_messageInfo_DatabaseStrings.DiscardUnknown(m)
}

var xxx_messageInfo_DatabaseStrings proto.InternalMessageInfo

func (m *DatabaseStrings) GetValues() []string {
	if m != nil {
		return m.Values
	}
	return nil
}

func init() {
	proto.RegisterType((*DatabaseEmpty)(nil), "proto.DatabaseEmpty")
	proto.RegisterType((*DatabaseResponse)(nil), "proto.DatabaseResponse")
	proto.RegisterType((*DatabaseID)(nil), "proto.DatabaseID")
	proto.RegisterType((*DatabaseIDs)(nil), "proto.DatabaseIDs")
	proto.RegisterType((*DatabaseString)(nil), "proto.DatabaseString")
	proto.RegisterType((*DatabaseStrings)(nil), "proto.DatabaseStrings")
}

func init() { proto.RegisterFile("database.proto", fileDescriptor_b90fe3356ea5df07) }

var fileDescriptor_b90fe3356ea5df07 = []byte{
	// 165 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4b, 0x49, 0x2c, 0x49,
	0x4c, 0x4a, 0x2c, 0x4e, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x05, 0x53, 0x4a, 0xfc,
	0x5c, 0xbc, 0x2e, 0x50, 0x09, 0xd7, 0xdc, 0x82, 0x92, 0x4a, 0x25, 0x2d, 0x2e, 0x01, 0x98, 0x40,
	0x50, 0x6a, 0x71, 0x41, 0x7e, 0x5e, 0x71, 0xaa, 0x90, 0x18, 0x17, 0x5b, 0x51, 0x6a, 0x71, 0x69,
	0x4e, 0x89, 0x04, 0xa3, 0x02, 0xa3, 0x06, 0x4f, 0x10, 0x94, 0xa7, 0xa4, 0xc4, 0xc5, 0x05, 0x53,
	0xeb, 0xe9, 0x22, 0x24, 0xc2, 0xc5, 0x5a, 0x96, 0x98, 0x53, 0x9a, 0x0a, 0x56, 0xc4, 0x12, 0x04,
	0xe1, 0x28, 0xa9, 0x72, 0x71, 0x23, 0xd4, 0x14, 0x83, 0x8c, 0x02, 0x8b, 0x17, 0x4b, 0x30, 0x2a,
	0x30, 0x6b, 0xb0, 0x04, 0x41, 0x79, 0x4a, 0x6a, 0x5c, 0x7c, 0x30, 0x65, 0xc1, 0x25, 0x45, 0x99,
	0x79, 0xe9, 0xa8, 0xc6, 0x71, 0xc2, 0x8c, 0xd3, 0xe4, 0xe2, 0x47, 0x55, 0x87, 0x6e, 0x24, 0x27,
	0xcc, 0xc8, 0x24, 0x36, 0xb0, 0x0f, 0x8d, 0x01, 0x01, 0x00, 0x00, 0xff, 0xff, 0xca, 0xc2, 0xed,
	0xbe, 0xfa, 0x00, 0x00, 0x00,
}
