// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: permission.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for PermissionService service

type PermissionService interface {
	FindOneByID(ctx context.Context, in *DatabaseID, opts ...client.CallOption) (*DatabaseResponse, error)
	FindManyByID(ctx context.Context, in *DatabaseIDs, opts ...client.CallOption) (*DatabaseResponse, error)
	FindOneByName(ctx context.Context, in *DatabaseString, opts ...client.CallOption) (*DatabaseResponse, error)
}

type permissionService struct {
	c    client.Client
	name string
}

func NewPermissionService(name string, c client.Client) PermissionService {
	if c == nil {
		c = client.NewClient()
	}
	if len(name) == 0 {
		name = "proto"
	}
	return &permissionService{
		c:    c,
		name: name,
	}
}

func (c *permissionService) FindOneByID(ctx context.Context, in *DatabaseID, opts ...client.CallOption) (*DatabaseResponse, error) {
	req := c.c.NewRequest(c.name, "PermissionService.FindOneByID", in)
	out := new(DatabaseResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *permissionService) FindManyByID(ctx context.Context, in *DatabaseIDs, opts ...client.CallOption) (*DatabaseResponse, error) {
	req := c.c.NewRequest(c.name, "PermissionService.FindManyByID", in)
	out := new(DatabaseResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *permissionService) FindOneByName(ctx context.Context, in *DatabaseString, opts ...client.CallOption) (*DatabaseResponse, error) {
	req := c.c.NewRequest(c.name, "PermissionService.FindOneByName", in)
	out := new(DatabaseResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for PermissionService service

type PermissionServiceHandler interface {
	FindOneByID(context.Context, *DatabaseID, *DatabaseResponse) error
	FindManyByID(context.Context, *DatabaseIDs, *DatabaseResponse) error
	FindOneByName(context.Context, *DatabaseString, *DatabaseResponse) error
}

func RegisterPermissionServiceHandler(s server.Server, hdlr PermissionServiceHandler, opts ...server.HandlerOption) error {
	type permissionService interface {
		FindOneByID(ctx context.Context, in *DatabaseID, out *DatabaseResponse) error
		FindManyByID(ctx context.Context, in *DatabaseIDs, out *DatabaseResponse) error
		FindOneByName(ctx context.Context, in *DatabaseString, out *DatabaseResponse) error
	}
	type PermissionService struct {
		permissionService
	}
	h := &permissionServiceHandler{hdlr}
	return s.Handle(s.NewHandler(&PermissionService{h}, opts...))
}

type permissionServiceHandler struct {
	PermissionServiceHandler
}

func (h *permissionServiceHandler) FindOneByID(ctx context.Context, in *DatabaseID, out *DatabaseResponse) error {
	return h.PermissionServiceHandler.FindOneByID(ctx, in, out)
}

func (h *permissionServiceHandler) FindManyByID(ctx context.Context, in *DatabaseIDs, out *DatabaseResponse) error {
	return h.PermissionServiceHandler.FindManyByID(ctx, in, out)
}

func (h *permissionServiceHandler) FindOneByName(ctx context.Context, in *DatabaseString, out *DatabaseResponse) error {
	return h.PermissionServiceHandler.FindOneByName(ctx, in, out)
}
