// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: user.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for UserService service

type UserService interface {
	FindOneByID(ctx context.Context, in *DatabaseID, opts ...client.CallOption) (*DatabaseResponse, error)
	FindManyByID(ctx context.Context, in *DatabaseIDs, opts ...client.CallOption) (*DatabaseResponse, error)
	FindOneByUsername(ctx context.Context, in *DatabaseString, opts ...client.CallOption) (*DatabaseResponse, error)
	FindManyByUsername(ctx context.Context, in *DatabaseStrings, opts ...client.CallOption) (*DatabaseResponse, error)
	FindOneByEmail(ctx context.Context, in *DatabaseString, opts ...client.CallOption) (*DatabaseResponse, error)
	FindManyByEmail(ctx context.Context, in *DatabaseStrings, opts ...client.CallOption) (*DatabaseResponse, error)
}

type userService struct {
	c    client.Client
	name string
}

func NewUserService(name string, c client.Client) UserService {
	if c == nil {
		c = client.NewClient()
	}
	if len(name) == 0 {
		name = "proto"
	}
	return &userService{
		c:    c,
		name: name,
	}
}

func (c *userService) FindOneByID(ctx context.Context, in *DatabaseID, opts ...client.CallOption) (*DatabaseResponse, error) {
	req := c.c.NewRequest(c.name, "UserService.FindOneByID", in)
	out := new(DatabaseResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userService) FindManyByID(ctx context.Context, in *DatabaseIDs, opts ...client.CallOption) (*DatabaseResponse, error) {
	req := c.c.NewRequest(c.name, "UserService.FindManyByID", in)
	out := new(DatabaseResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userService) FindOneByUsername(ctx context.Context, in *DatabaseString, opts ...client.CallOption) (*DatabaseResponse, error) {
	req := c.c.NewRequest(c.name, "UserService.FindOneByUsername", in)
	out := new(DatabaseResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userService) FindManyByUsername(ctx context.Context, in *DatabaseStrings, opts ...client.CallOption) (*DatabaseResponse, error) {
	req := c.c.NewRequest(c.name, "UserService.FindManyByUsername", in)
	out := new(DatabaseResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userService) FindOneByEmail(ctx context.Context, in *DatabaseString, opts ...client.CallOption) (*DatabaseResponse, error) {
	req := c.c.NewRequest(c.name, "UserService.FindOneByEmail", in)
	out := new(DatabaseResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userService) FindManyByEmail(ctx context.Context, in *DatabaseStrings, opts ...client.CallOption) (*DatabaseResponse, error) {
	req := c.c.NewRequest(c.name, "UserService.FindManyByEmail", in)
	out := new(DatabaseResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for UserService service

type UserServiceHandler interface {
	FindOneByID(context.Context, *DatabaseID, *DatabaseResponse) error
	FindManyByID(context.Context, *DatabaseIDs, *DatabaseResponse) error
	FindOneByUsername(context.Context, *DatabaseString, *DatabaseResponse) error
	FindManyByUsername(context.Context, *DatabaseStrings, *DatabaseResponse) error
	FindOneByEmail(context.Context, *DatabaseString, *DatabaseResponse) error
	FindManyByEmail(context.Context, *DatabaseStrings, *DatabaseResponse) error
}

func RegisterUserServiceHandler(s server.Server, hdlr UserServiceHandler, opts ...server.HandlerOption) error {
	type userService interface {
		FindOneByID(ctx context.Context, in *DatabaseID, out *DatabaseResponse) error
		FindManyByID(ctx context.Context, in *DatabaseIDs, out *DatabaseResponse) error
		FindOneByUsername(ctx context.Context, in *DatabaseString, out *DatabaseResponse) error
		FindManyByUsername(ctx context.Context, in *DatabaseStrings, out *DatabaseResponse) error
		FindOneByEmail(ctx context.Context, in *DatabaseString, out *DatabaseResponse) error
		FindManyByEmail(ctx context.Context, in *DatabaseStrings, out *DatabaseResponse) error
	}
	type UserService struct {
		userService
	}
	h := &userServiceHandler{hdlr}
	return s.Handle(s.NewHandler(&UserService{h}, opts...))
}

type userServiceHandler struct {
	UserServiceHandler
}

func (h *userServiceHandler) FindOneByID(ctx context.Context, in *DatabaseID, out *DatabaseResponse) error {
	return h.UserServiceHandler.FindOneByID(ctx, in, out)
}

func (h *userServiceHandler) FindManyByID(ctx context.Context, in *DatabaseIDs, out *DatabaseResponse) error {
	return h.UserServiceHandler.FindManyByID(ctx, in, out)
}

func (h *userServiceHandler) FindOneByUsername(ctx context.Context, in *DatabaseString, out *DatabaseResponse) error {
	return h.UserServiceHandler.FindOneByUsername(ctx, in, out)
}

func (h *userServiceHandler) FindManyByUsername(ctx context.Context, in *DatabaseStrings, out *DatabaseResponse) error {
	return h.UserServiceHandler.FindManyByUsername(ctx, in, out)
}

func (h *userServiceHandler) FindOneByEmail(ctx context.Context, in *DatabaseString, out *DatabaseResponse) error {
	return h.UserServiceHandler.FindOneByEmail(ctx, in, out)
}

func (h *userServiceHandler) FindManyByEmail(ctx context.Context, in *DatabaseStrings, out *DatabaseResponse) error {
	return h.UserServiceHandler.FindManyByEmail(ctx, in, out)
}
